name: Lint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  codespell:
    name: Check spelling all files with codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install codespell==2.2.4
      - name: Check spelling with codespell
        run: codespell --ignore-words=codespell.txt --skip="./doctrine/de.html,./doctrine/es.html,./doctrine/fr.html,./.git,./_posts/200*-*,./_posts/201*-*,./assets/200*,./assets/201*,./_posts/*sao-paolo.markdown" || exit 1
